// get a full list of courses
const courses = [
  "Certificate in Agribusiness",
  "Certificate in Business Administration",
  "Diploma in Architecture",
  "Diploma in Agribusiness Management and Technology",
  "Diploma in Automobile Engineering",
  "Diploma in Biomedical Engineering",
  "Diploma in Business Administration",
  "Diploma in Business Administration with Accounting",
  "Diploma in Business Administration with Marketing",
  "Diploma in Chemical Engineering",
  "Diploma in Civil Engineering",
  "Diploma in Computer Engineering",
  "Diploma in Computer Science",
  "Diploma in Electrical and Electronic Engineering",
  "Diploma in Electronics and Telecommunication Engineering",
  "Diploma in Environmental Science and Technology",
  "Diploma in Food Science and Technology",
  "Diploma in Highway Engineering",
  "Diploma in Information and Communication Technology",
  "Diploma in Laboratory Science and Technology",
  "Diploma in Mechanical Engineering",
  "Diploma in Mechatronics Engineering",
  "Diploma in Mining Engineering",
  "Diploma in Quantity Surveying",
  "Diploma in Renewable Energy Technology",
  "Diploma in Secretarial Studies",
  "Bachelor of Agribusiness Management and Technology",
  "Bachelor of Business Administration",
  "Bachelor of Computer Science",
  "Bachelor of Engineering in Chemical and Process Engineering",
  "Bachelor of Engineering in Civil Engineering",
  "Bachelor of Engineering in Computer Engineering",
  "Bachelor of Engineering in Data Science",
  "Bachelor of Engineering in Electrical and Electronic Engineering",
  "Bachelor of Engineering in Mechanical Engineering",
  "Bachelor of Engineering in Mechatronics Engineering",
  "Bachelor of Engineering in Renewable Energy",
  "Bachelor of Engineering in Telecommunication Engineering",
  "Bachelor of Information and Communication Technology",
  "Bachelor of Landscape Architecture",
  "Bachelor of Science in Food Science and Technology",
  "Bachelor of Science in Information and Computer Networking",
  "Bachelor of Science in Laboratory Science and Technology",
  "Bachelor of Science in Natural Resource Conservation",
  "Bachelor of Science with Education",
  "Bachelor of Technology in Architecture",
  "Bachelor of Technical Education in Civil Engineering",
  "Bachelor of Technical Education in Electrical and Electronic Engineering",
  "Bachelor of Technical Education in Mechanical Engineering",
  "Postgraduate Diploma in Technical Education",
  "Master of Science in Civil Engineering",
  "Master of Science in Information Technology",
  "Master of Science in Mechanical Engineering",
  "Master of Science in Power Systems Engineering",
  "Doctor of Philosophy in Information System Engineering",
  "Doctor of Philosophy in Mechanical Engineering",
];

module.exports = courses;
