site_name: IPT
site_url: https://njoxpy.github.io/Project-Docs-IPT/
site_description: IPT documentation with Markdown.
site_author: NjoxPy

# Repository
repo_name: Project-Docs-IPT
repo_url: https://github.com/Njoxpy/Project-Docs-IPT
# edit_uri: edit/main/docs/

# navigation
nav:
  - index.md
  - project-charter.md
  - requirements.md
  - feasibility-study.md
  - project-plan.md
  - system-design.md
  - testing-plan.md
  - deployment-plan.md
  - user-manual.md
  - maintenance-plan.md
  - database: database/database.md
  - Report: database/report.md

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
    logo: material/book-open-page-variant
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
# repo_url: https://github.com/mkdocs/mkdocs/
# edit_uri: blob/master/docs/

# nav:

#   # folder structure for the repository
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Njoxpy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Njox16
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/godbless-nyagawa/

plugins:
  - search
  - tags

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Njoxpy" target="_blank" rel="noopener">Godbless Nyagawa(NjoxPy)</a>
